### ISSUE TITLE
Create HamburgerMenuView

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#11]
**Description**  
- Create HamburgerMenuView to navigate throughout the different app views

---

**Task List**  
- [x] Step 1: Create HamburgerMenuView File
- [x] Step 2: Create button to navigate to Home View
- [x] Step 3: Create button to navigate to DollStatus View
- [x] Step 4: Create button to navigate to GameCatalog View
- [x] Step 5: Create button to navigate to Closet View
- [ ] Step 6: Create logout button
- [ ] Step 7: Call HamburgerMenuView Struct into Home, DollStatus, GameCatalog, and Closet view

---

**Acceptance Criteria**  
- [ ] All buttons successfully navigate to desired views
- [ ] Hamburger menu is correctly set up and expands & retracts upon touch
- [ ] Logout button logic consistent with heart decay element
- [ ] HamburgerMenu dimensions fit every view & does not obstruct anything

---

**Resources / References**  
- [Medium Article](https://medium.com/geekculture/side-menu-in-ios-swiftui-9fe1b69fc487)
- [LogOut](https://www.youtube.com/watch?v=7LXEU5QzPOU)
- [LogOut](https://firebase.google.com/docs/auth/web/password-auth)
<img width="69" alt="Screenshot 2024-10-23 at 7 43 57 PM" src="https://github.com/user-attachments/assets/5ee789f4-ef0a-48c5-b19d-9412e2fcc4eb">

**Comment by nicolec082202** [comment]
Use [SF Symbols](https://developer.apple.com/sf-symbols/) as placeholder assets for now since assets have not been completed
