### ISSUE TITLE
Create Main Menu Scene

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#12]
**Description**  
- Create main menu scene for games
---

**Task List**  
- [ ] Step 1: Update main menu scene UI based on sketch
- [ ] Step 2: Update both WorkOutGameMainMenuScene and MatchingGameMainMenuScene
- [ ] Step 3: Use equippedBaby binding variable to bring current equipped baby into main menu scenes
- [ ] Step 4: Add button to return back to GameCatalogView
---

**Acceptance Criteria**  
- [ ] Main Menu Scene follows sketch
- [ ] Current equipped baby is shown on screen
- [ ] Start game button in WorkOutGameMainMenuScene successfully launches level 1 of workout game 
- [ ] Start game button in MatchingGameMainMenuScene successfully launches level 1 of matching game 
- [ ] Current equipped baby sprite is passed via closet view to level 1 to play game 
- [ ] Buttons to return to GameCatalogView are functional

---

**Resources / References**  
- [Branding Kit](https://www.notion.so/Branding-Kit-1156a25db7be80f8a976f06cfcd6a000?pvs=4)
- [SpriteKit Notion Resources](https://www.notion.so/SpriteKit-1156a25db7be800e8db4
- [Matching Game MainMenu Scene Assets/Sketches](https://drive.google.com/drive/folders/1u816eaRCJoQAh3tX_HA7tf0JOkY5CUEo?usp=sharing)
- [WorkoutGame MainMenu Scene Assets/Sketches](https://drive.google.com/drive/folders/1gLXGBcUExazYTmNS81bXtGb5J-XQErhu?usp=sharing)

**Note**
-Background image should be imported, background itself will be transparent at first, you need to add in the color background by color matching with the layout sketch provided
- If you have trouble with the clickable area of the button (i.e. area to click is larger than should be), try to crop the background of button images/make them larger
