### ISSUE TITLE
Create sketch for GameCatalogView

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#23]
**Description**  
- Create a sketch for the GameCatalogView layout

---

**Task List**  
- [ ] Step 1: Create a sketch for the GameCatalogView layout 
- [ ] Step 2: Create title/logo asset
- [ ] Step 3: Create Work Out Game button asset
- [ ] Step 4: Create Card Matching game button asset

---

**Acceptance Criteria**  
- [ ] Sketch matches branding guide
- [ ] Title/logo asset created
- [ ] Work Out Game button asset created
- [ ] Card Matching game button asset created

---

**Resources / References**  
- [Branding Kit](https://www.notion.so/Branding-Kit-1156a25db7be80f8a976f06cfcd6a000?pvs=4#1276a25db7be80dcb706ee0bb290350a)
