### ISSUE TITLE
Edit babies Design

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#24]
**Description**  
- Create 5 baby sprites based on the original nice babies

---

**Task List**  
- [ ] Step 1: Nice baby sheep sprite
- [ ] Step 2: Nice baby monkey sprite
- [ ] Step 3: Nice baby fish sprite
- [ ] Step 4: Nice baby cow sprite
- [ ] Step 5: Nice baby panda sprite
- [ ] Step 6: Nice baby bunny sprite

---

**Acceptance Criteria**  
- [ ] Create Nice baby sheep sprite
- [ ] Create Nice baby monkey sprite
- [ ] Create Nice baby fish sprite
- [ ] Create Nice baby cow sprite
- [ ] Create Nice baby panda sprite
- [ ] Create Nice baby bunny sprite

---

**Resources / References**  
- [Canva Link](https://www.canva.com/design/DAGNr_ZfOlk/kWm7ujCNJikbS5OcZmKVyA/edit?utm_content=DAGNr_ZfOlk&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)

**Comment by Coconut-Axolotl** [comment]
![Bunny 2](https://github.com/user-attachments/assets/49cf96c5-9c7a-4aaa-94e5-610aea37ea77)
![Bunny 1](https://github.com/user-attachments/assets/28638f66-2f8c-414b-8f76-9c485668c978)
![Bunny 3](https://github.com/user-attachments/assets/c9feaec8-4f92-4bfd-84cf-cb78b07f88fa)
