### ISSUE TITLE
Create Home Page Assets

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#25]
**Description**  
- Create home page assets

---

**Task List**  
- [ ] Create Laptop Asset
- [ ] Create Desk Asset
- [ ] Create Shelf Asset
- [ ] Create Window Asset
- [ ] Create Bed Asset
- [ ] Create Rug Asset 

---

**Acceptance Criteria**  
- [ ] Laptop Asset is in correct format (.jpg/.png) and following style guide
- [ ] Shelf Asset is in correct format (.jpg/.png) and following style guide
- [ ] Rest of assets can be individual or part of a pre-existing background

---

**Resources / References**  
- [Notion documentation](https://www.notion.so/Branding-Kit-1156a25db7be80f8a976f06cfcd6a000?pvs=4)

**Comment by carolinhr** [comment]
https://www.figma.com/design/QOgO6Hh8bwOQrN4HCFvzqu/sketchez?node-id=16-775&t=yFs9Mr1hvXNwuOGC-1

assets that can be used if we like the home view shown in figma
![Image](https://github.com/user-attachments/assets/5ee0352e-1a93-4065-83a2-915f983fb58a)
![Image](https://github.com/user-attachments/assets/11c23671-adaf-4a9e-b05f-a8733c934a23)

**Comment by carolinhr** [comment]
still pending: add more assets from canva
