### ISSUE TITLE
Assets for HamburgerMenuView

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#27]
**Description**  
- Create icon assets for Hamburger Menu

---

**Task List**  
- [ ] Step 1: Create home button icon asset
- [ ] Step 2: Create doll button icon asset
- [ ] Step 3: Create laptop button icon asset
- [ ] Step 4: Create shelf/closet button icon asset
- [ ] Step 5: Create logout button asset

---

**Acceptance Criteria**  
- [ ] Home button icon asset created
- [ ] Doll button icon asset created
- [ ] Laptop button icon asset created
- [ ] Shelf/closet button icon asset created
- [ ] Logout button icon asset created

---

**Resources / References**  
- [Notion documentation](https://www.notion.so/Branding-Kit-1156a25db7be80f8a976f06cfcd6a000?pvs=4)

**Comment by carolinhr** [comment]
Closet
![Image](https://github.com/user-attachments/assets/4e630492-a7d5-4d5b-bd22-db3094861154)

Laptop
![Image](https://github.com/user-attachments/assets/fa6b90a1-cc95-484d-99b2-08f371d81b17)

Doll
![Image](https://github.com/user-attachments/assets/07a19d15-f3d8-4a48-b765-51dbbd60864f)

Home
![Image](https://github.com/user-attachments/assets/bb889c4a-83cc-4d11-b62f-998841e3c807)

Logout
![Image](https://github.com/user-attachments/assets/307b6bde-7d44-41e3-ac4e-bcff928e9880)
