### ISSUE TITLE
Code Loading Page For Games

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#28]
**Description**  
- Create Loading Page for all games
- This same loading page can be re-used for each mini game

---

**Task List**  
- [ ] Step 0: Ensure you pull from main to obtain WorkOutGameLoadingScene and MatchingGameLoadingScene loading gif
- [ ] Step 1: Add black background image
- [ ] Step 2: Add "Loading" text
- [ ] Step 3: Re-position flower loading animation
- [ ] Step 4: Ensure loading page code is duplicated in WorkOutGameLoadingScene and MatchingGameLoadingScene

---

**Acceptance Criteria**  
- [ ] Loading scene is shown only while game is launching 
- [ ] Animation is shown as expected (adjust position to show in horizontal view)
- [ ] Loading page leads into WorkOutGameStartScene
- [ ] Page is oriented horizontally (command + right arrow to adjust simulator)

---

**Resources / References**  
- How to Create Animation in SpriteKit: https://www.youtube.com/watch?v=lXTTgBQuw8M&t=625s

---
