### ISSUE TITLE
Fix app logging out every time

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#30]
**Description**  
-Bug in which app logs user out every time app is exited

---

**Task List**  
- [ ] Step 1: Ensure user stays logged in even if app has been closed and program hasn't been terminated

---

**Acceptance Criteria**  
- [ ] User remains logged in after closing simulator
- [ ] User remains logged in after closing app on phone
- [ ] User is logged out if program is terminated

---

**Resources / References**  
- [Stack Overflow] https://stackoverflow.com/questions/71052802/how-to-keep-user-logged-in-using-firebase-in-swift
- [Firebase] https://firebase.google.com/docs/auth/web/auth-state-persistence

---
