### ISSUE TITLE
Create Main Menu Scene Sketch

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#32]
**Description**  
- Create Sketch for WorkOutGameMainMenu scene page and MatchingGameMainMenu scene page
- The layouts can be identical but colors & title/logo should be unique to identify each game

---

**Task List**  
- [ ] Step 1: Create Sketch for main menu scene page
- [ ] Step 2: Include Button to start game
- [ ] Step 3: Include section to display selected sprite/baby
- [ ] Step 4: Include a button to go back to the game catalog view

---

**Acceptance Criteria**  
- [ ] Sketch matches branding kit
- [ ] Sketch includes necessary buttons and assets
- [ ] Most elements can be shared 

---

**Resources / References**  
- [Branding Kit](https://www.notion.so/Branding-Kit-1156a25db7be80f8a976f06cfcd6a000?pvs=4)
