### ISSUE TITLE
Create WorkOutGame Level 1 Scene

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#33]
**Description**  
- Create level 1 for workout game 

---

**Task List**  
- [ ] Step 1: Add background elements
- [ ] Step 2: Add obstacles
- [ ] Step 3: Add sprite -- type alpha, affected by gravity
- [ ] Step 4: Add joystick
- [ ] Step 5: Add stars/coins to replenish health
- [ ] Step 6: Add health bar (out of 100%)
- [ ] Step 7: Add goal/level complete element

---

**Acceptance Criteria**  
- [ ] Background, obstacles, health replenish element, health bar, goal/level complete match sketch
- [ ] Sprite corresponds to the once chosen in the main menu
- [ ] Joystick functions as intended
- [ ] Hitting an obstacle depletes health by 10%
- [ ] Collecting star/coin replenishes 5% health
- [ ] When game ends, gameCompleted boolean is set to true

---

**Resources / References**  
- [Game Reference](https://www.youtube.com/watch?v=1H9EG15mycI)

**Comment by nicolec082202** [comment]
For now, just make game with sample game assets--focus on functionality and we can replace assets once they're finalized
