### ISSUE TITLE
Create WorkOutGame Level 1 Scene Sketch

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#34]
**Description**  
- Create level 1 for workout game sketch

---

**Task List**  
- [ ] Step 1: Create background assets
- [ ] Step 2: Create obstacle assets
- [x] Step 5: Create stars/coins to replenish health assets
- [x] Step 6: Create health bar (out of 100%) asset
- [x] Step 7: Create goal/level complete asset
- [x] Step 8: Create a 'dead'/'game over' pop-up 
- [x] Step 9: Create a 'game complete' pop-up 
- [ ] Step 10: Create a sketch of how elements should be places/laid out

---

**Acceptance Criteria**  
- [ ] All necessary assets created
- [ ] Sketch matches branding kit

---

**Resources / References**  
- [Branding Kit](https://www.notion.so/Branding-Kit-1156a25db7be80f8a976f06cfcd6a000?pvs=4)
- [Sample Game](https://m.youtube.com/watch?v=1H9EG15mycI)
- [Sample game completion/Config Assets](https://www.freepik.com/premium-vector/graphical-interface-elements-game-design-pink-includes-buttons-with-icons-progress-bar-store-main-menu-windows_12386055.htm)
-Note: may not use these -- TBD

**Comment by allisonr5002** [comment]
Background:
![Image](https://github.com/user-attachments/assets/f916e3d4-3d03-4298-b31d-7d0ffc7a3cd1)

Star/Points:
![Image](https://github.com/user-attachments/assets/4e25b35b-7728-4f95-9eb0-905e126310ee)

Pink Splash:
![Image](https://github.com/user-attachments/assets/7b2f102a-968e-4407-9a14-ea661b4d53af)

Blue Splash:
![Image](https://github.com/user-attachments/assets/54148503-d299-49a3-838e-5cf62cf1fd3a)

Yellow Splash:
![Image](https://github.com/user-attachments/assets/dba5a905-d576-4196-a0ba-fad1fbcd180f)

Blue Blocker:
![Image](https://github.com/user-attachments/assets/f0fc9bd4-8358-4192-9961-8c303e2e39da)

Green Blocker:
![Image](https://github.com/user-attachments/assets/d20c8ec9-e3d2-4521-8103-6c2e4d54e7c3)

Purple Blocker:
![Image](https://github.com/user-attachments/assets/f020b423-f93a-46f8-a3ca-aaab50535b96)
