### ISSUE TITLE
Create ClosetView UI

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#35]
**Description**  
- Create closetView based on sketch
- This view will allow users to equip a baby that will be shown in DollStatusView and used to play the mini games

---

**Task List**  
- [ ] Step 1: Create presentation sheet to display closet view
- [ ] Step 2: Create carousel that users can swipe through displaying all 6 babies 
- [ ] Step 3: Create 'equip/choose baby' button that updates the binding variable 'equippedBaby' 
- [ ] Step 4: When button is pressed, dismiss presentation sheet

---

**Acceptance Criteria**  
- [ ] UI matches sketch
- [ ] Carousel is responsive 
- [ ] When baby is equipped, equippedBaby variable string is updated to chosen baby
- [ ] Equipped baby is now seen in DollStatusView and in Main Menu of mini games

---

**Resources / References**  
- [Carousel View](https://edolorenza.medium.com/creating-a-carousel-in-swiftui-619121268949)
- Review existing code to see how presentation sheets are created & dismissed
