### ISSUE TITLE
Create Matching Game Level 1 Scene Sketch

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#36]
**Description**  
- Create sketch for level 1 of matching game

---

**Task List**  
- [ ] Step 1: Create background asset
- [x] Step 2: Create Card background asset
- [x] Step 3: Create Card game layout
- [ ] Step 4: Create timer asset 

---

**Acceptance Criteria**  
- [ ] All necessary assets created
- [ ] Sketch matches branding kit

---

**Resources / References**  
- [Branding Kit](https://www.notion.so/Branding-Kit-1156a25db7be80f8a976f06cfcd6a000?pvs=4)
- [Sample Extra Assets](https://www.freepik.com/premium-vector/graphical-interface-elements-game-design-pink-includes-buttons-with-icons-progress-bar-store-main-menu-windows_12386055.htm)

**Comment by nicolec082202** [comment]
The matching game will work as follows:

12 cards will be laid out on the screen to begin with. All cards will be upside down. At each turn, the user will be allowed to tap two of the cards. When they tap on a card, it will flip to reveal the baby icon on the other side. If the two cards have different babies, they will flip back over. If the two cards have the same baby, they will remain flipped over (baby side), and the user will gain 10 points. The game continues for 2 minutes or until the user is able to match all of the cards.

**Comment by Ztos0** [comment]
![Card Game  Layout (2)](https://github.com/user-attachments/assets/0264c467-2ebc-4d46-94b9-f5333194e651)
![Card Game  Layout (3)](https://github.com/user-attachments/assets/4ecbc585-299a-4198-b9c5-67731d22cdb0)
![Card Game  Layout (4)](https://github.com/user-attachments/assets/9a882355-85a8-473f-a37c-09cce1761947)
![Card Game  Layout (5)](https://github.com/user-attachments/assets/cce2da71-b4e9-4a80-aab1-7e673befe26e)
![Card Game  Layout (6)](https://github.com/user-attachments/assets/d5bb8513-658c-469a-a59f-882b0b29df31)
![Card Game  Layout](https://github.com/user-attachments/assets/56ab2d98-e80d-4e5b-9a53-93e73513e095)
