### ISSUE TITLE
Create Matching Game Level 1 Scene

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#37]
**Description**  
- Create level 1 for matching game 

---

**Task List**  
- [ ] Step 1: Set up background
- [ ] Step 2: Create cards & add background (4 x 3)
- [ ] Step 3: Randomize nice baby assets on back side of cards (should be 2 of 
- [ ] Step 4: Create card flip animation
- [ ] Step 5: Set up timer (1 minute)
- [ ] Step 6: For each 
- [ ] Step 6: After time runs out, game over page is presented
- [ ] Step 7: Game over page shows score

---

**Acceptance Criteria**  
- [ ] All necessary assets created
- [ ] Sketch matches branding kit

---

**Resources / References**  
- [Branding Kit](https://www.notion.so/Branding-Kit-1156a25db7be80f8a976f06cfcd6a000?pvs=4)
