### ISSUE TITLE
Create Closet View Sketch

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#4]
**Description**  
- Create sketch for closet view 
- Baby chosen in closet view becomes baby displayed in DollStatusView (equippedbaby)

---

**Task List**  
- [x] Step 1: Create sketch for closet view based on video attached in comment below
---

**Acceptance Criteria**  
- [ ] Sketch matches branding kit
- [ ] Babies are shown on carousel that users can swipe through
- [ ] Includes button to 'equip' baby

---

**Resources / References**  
- [Branding Kit](https://www.figma.com/design/SHU630W8Cn50MfTaLoUPZf/Project-Type?node-id=0-1&t=gCciU4ol2Ykzq4ZP-1)

**Comment by nicolec082202** [comment]
https://github.com/user-attachments/assets/5bdb1f6b-cce6-4f96-8bdb-5e1d62bb808b

**Comment by carolinhr** [comment]
https://www.figma.com/proto/QOgO6Hh8bwOQrN4HCFvzqu/sketchez?node-id=0-1&t=aE6CJTtUeNafskCu-1

![Image](https://github.com/user-attachments/assets/d2111e8b-c87e-4587-bf3a-6f8b2c9cbb0e)

**Comment by carolinhr** [comment]
revised
![Image](https://github.com/user-attachments/assets/25154dda-d077-402b-9541-d9feee68132d)
