### ISSUE TITLE
Widget Sketches

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#45]
**Description**  
- Create a sketch for a small game widget
- Widget should display niceBaby sprite, hearts status, and a button to launch the app

---

**Task List**  
- [ ] Step 1: Create a sketch for the widget layout
- [ ] Step 2: Create button to launch app (within widget)
---

**Acceptance Criteria**  
- [ ] Sketch follows branding kit/samples
- [ ] Small, medium, and large sketches will be the same, just different screen sizes 

---

**Resources / References**  
- [Branding Kit](https://www.notion.so/Branding-Kit-1156a25db7be80f8a976f06cfcd6a000?pvs=4)![Image](https://github.com/user-attachments/assets/57109cd8-500a-4969-88a3-bd217d818962)
![Image](https://github.com/user-attachments/assets/866d13bf-f97a-48a7-bc6e-5896c314ebdb)

**Comment by carolinhr** [comment]
https://www.figma.com/design/QOgO6Hh8bwOQrN4HCFvzqu/sketchez?node-id=106-5683&t=XXd2S9XCLSlpaZmF-1
![Image](https://github.com/user-attachments/assets/a81d89bc-2177-4685-b1ca-5ce0c834f129)
