### ISSUE TITLE
Update GameCatalogView UI

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#5]
**Description**  
- Update GameCatalogView  based on sketch

---

**Task List**  
- [ ] Step 1: Navigate to GameCatalogView File
- [ ] Step 2: Replace any placeholder assets within Buttons newly creates ones (replace Text label in button with Image label and pass in the string name of the newly imported asset)
- [ ] Step 3: Re-position buttons based on sketch in the drive
- [ ] Step 4: Add in 'Choose game' bubble header on top of view
- [ ] Step 5: Add in neutral sprite version of current equippedBaby between the game buttons and Choose Game bubble header
- [ ] Step 6: Add in background color for view using Color (r:,g:, b:)

---

**Acceptance Criteria**  
- [ ] New UI matches sketch
- [ ] All new assets are imported correctly
- [ ] Buttons continue to work properly
- [ ] Buttons launch the correct games

---
**References**
[Drive Link](https://drive.google.com/drive/folders/1pmug6ql01SIDdpZCzSiIJEtQIGP8q2Zj?usp=sharing)
---
**Notes**
-Background image should be imported, background itself will be transparent at first, you need to add in the color background by color matching with the layout sketch provided
-There are 3 buttons on the sketch, leave one of them without any logic because the third game has not been made yet

**Comment by nicolec082202** [comment]
Need sketch of GameCatalogView
