### ISSUE TITLE
Create Flappy Bird Game Sketch/Assets

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#53]
**Description**  
- Create a sketch/layout for flappy bird game
- Create assets for flappy bird game

---

**Task List**  
- [ ] Step 1: Create/Find background (sky)
- [ ] Step 2: Create tube assets
- [ ] Step 3: Create simple sketch of how tubes/sprite will be laid out

---

**Acceptance Criteria**  
- [ ] Background matches branding kit
- [ ] Tube assets match branding kit

---

**Resources / References**  
-[Branding Kit](https://www.notion.so/Branding-Kit-1156a25db7be80f8a976f06cfcd6a000?pvs=4)

![Image](https://github.com/user-attachments/assets/efe67332-398d-429f-80bc-339fcdd82253)
