### ISSUE TITLE
Update HomePageView UI

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#6]
**Description**  
- Update HomePageView based on sketch

---

**Task List**  
- [ ] Step 1: Replace any placeholder assets with newly creates ones (replace string parameter in Image() )
- [ ] Step 2: Adjust positioning of elements using x, y coordinates as needed

---

**Acceptance Criteria**  
- [ ] New UI matches sketch
- [ ] All new assets are imported correctly
- [ ] Buttons continue to work properly
- [ ] New assets are not overlapping/covering buttons

**Comment by nicolec082202** [comment]
Need to create updated assets:

Laptop
Table
Desk
Bed
Window
