### ISSUE TITLE
Add password restrictions

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#7]
Valid Passwords should:
1. Be minimum 8 characters
2. Have at least one number
3. Have at least one symbol

**Description**  
- Add password restrictions for users creating new accounts

---

**Task List**  
- [ ] Step 1: Update isValidPassword function in String View 

---

**Acceptance Criteria**  
- [ ] Passwords should be minimum 8 characters
- [ ] Passwords should have at least one number
- [ ] Passwords should have at least one symbol
- [ ] Passwords should be unique?
