### ISSUE TITLE
Add Username Restrictions 

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#8]
**Description**  
- Add username restrictions for users creating new accounts

---

**Task List**  
- [ ] Step 1: Update isValidUsername function in String View 

---

**Acceptance Criteria**  
- [ ] Usernames should be between 6-10 characters
- [ ] Usernames should only contain letters, numbers, _
- [ ] Usernames should be unique
