### ISSUE TITLE
Update LogInView UI

### ISSUE THREAD

**Issue by nicolec082202** [nicolec082202/NiceBabiesWorld#9]
**Description**  
- Update LogInView UI based on sketch

---

**Task List**  
- [ ] Step 1: Update Background
- [ ] Step 2: Update/add logo
- [ ] Step 3: Adjust text boxes
- [ ] Step 4: Update submit button

---

**Acceptance Criteria**  
- [ ] New UI matches sketch
- [ ] Everything on page remains functional

---

**Resources / References**  
- LogInView Sketch

**Comment by nicolec082202** [comment]
Need updated loginView sketch
